name: wear_stock
description: Wear Stcock
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.6
  flutter_spinkit: ^5.1.0
  hive_flutter: ^1.1.0
  watch_connectivity: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/stock.png